services:
  notifier-proxy:
    build: .
    ports:
      - "8100:8100"
    environment:
      SERVER_PORT: "8100"
      SIGNAL_CLI_SERVER_PORT: "8080"
    networks:
      - signal-network
    depends_on:
      - signal-cli-server

  cli-server:
    image: bbernhard/signal-cli-rest-api:latest
    ports:
      - "8101:8080"
    environment:
      MODE: native
    volumes:
      - signal-api-data:/home/.local/share/signal-cli
    networks:
      - signal-network
    restart: unless-stopped

networks:
  signal-network:
    driver: bridge

volumes:
  signal-api-data: